config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :revenues
  resources :expenses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/models/revenue.rb
class Revenue < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  
  def index
		@expenses = Expense.order(created_at: :asc)
	end

	def show
		@expense = Expense.find(params[:id])
	end

	def new
		@expense = Expense.new()
	end

	def edit
		@expense = Expense.find(params[:id])
	end

	def create
		#@expense = Expense.new(params[:expense])
		@expense = Expense.new(expense_params)
		if @expense.save
			redirect_to @expense, notice: "支出を登録しました"
		else
			render "new"
		end	
	end

	def update
		@expense = Expense.find(params[:id])
		#@expense.assign_attributes(params[:expense])
		@expense.assign_attributes(expense_params)
		if @expense.save
			redirect_to @expense, notice: "支出を登録しました"
		else
			render "new"
		end
	end

	def destroy
		@expense = Expense.find(params[:id])
		@expense.destroy
		redirect_to :expenses, notice: "支出を削除しました。"
	end
	
	private
		def expense_params
			params.require(:expense).permit(:name, :value, :description)
		end
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  
  def index
		@revenues = Revenue.order(created_at: :asc)
	end

	def show
		@revenue = Revenue.find(params[:id])
	end

	def new
		@revenue = Revenue.new()
	end

	def edit
		@revenue = Revenue.find(params[:id])
	end

	def create
		#@revenue = Expense.new(params[:revenue])
		@revenue = Revenue.new(revenue_params)
		if @revenue.save
			redirect_to @revenue, notice: "収入を登録しました"
		else
			render "new"
		end	
	end

	def update
		@revenue = Revenue.find(params[:id])
		#@revenue.assign_attributes(params[:revenue])
		@revenue.assign_attributes(revenue_params)
		if @revenue.save
			redirect_to @revenue, notice: "収入を登録しました"
		else
			render "new"
		end
	end

	def destroy
		@revenue = Revenue.find(params[:id])
		@revenue.destroy
		redirect_to :revenues, notice: "収入を削除しました。"
	end
	
	private
		def revenue_params
			params.require(:revenue).permit(:name, :value, :description)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "家計簿アプリへようこそ!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "家計簿アプリ"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/expenses/_form.html.erb
<%= link_to "支出一覧に戻る", :expenses %>
<table>
 <tr>
	 <th><%= form.label :name, "支出名" %></th>
	 <td><%= form.text_field :name %></td>
 </tr>
 <tr>
	 <th><%= form.label :value, "金額" %></th>
	 <td><%= form.number_field :value %></td>
 </tr>
 <tr>
	<th><%= form.label :description, "説明" %></th>
	<td><%= form.text_field :description %></td>
 </tr>
</table>

app/views/expenses/edit.html.erb
<h2>支出編集</h2>
<%= form_for @expense do |form| %>
	<%= render "form", form: form %>
	<div><%= form.submit %></div>
<% end %>

app/views/expenses/index.html.erb
<% @page_title = "支出一覧" %>
<h2><%= @page_title %></h2>

<%= link_to "支出の新規登録", :new_expense %>

<% if @expenses.present? %>
<table>
	<thead>
		<tr>
			<th>支出名</th>
			<th>金額</th>
			<th>備考</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @expenses.each do |expense| %>
			<tr>
				<td><%= expense.name %></td>
				<td><%= expense.value %></td>
				<td><%= expense.description %></td>
				<td>
				<%= link_to "編集", [:edit, expense] %>
				<%= link_to "削除", expense, method: :delete,
					data: { confirm: "本当に削除しますか？"} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<% else %>
	<p>登録されている支出がありません。</p>
<% end %>

app/views/expenses/new.html.erb
<h2>支出登録</h2>
<%= form_for @expense do |form| %>
	<%= render "form", form: form %>
	<div><%= form.submit %></div>
<% end %>

app/views/expenses/show.html.erb
<h2>支出の詳細</h2>

<%= link_to "編集", [:edit, @expense] %>
<%= link_to "支出一覧へ戻る", :expenses %>

<table>

	<tr>
    <th>支出名</th>
    <td><%= @expense.name %></td>
  </tr>
  
  <tr>
    <th>金額</th>
    <td><%= @expense.value %></td>
  </tr>

	<tr>
		<th>説明</th>
		<td><%= @expense.description %></td>
	</tr>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "家計簿アプリ", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/revenues/_form.html.erb
<%= link_to "収入一覧に戻る", :revenues %>
<table>
 <tr>
	 <th><%= form.label :name, "収入名" %></th>
	 <td><%= form.text_field :name %></td>
 </tr>
 <tr>
	 <th><%= form.label :value, "金額" %></th>
	 <td><%= form.number_field :value %></td>
 </tr>
 <tr>
	<th><%= form.label :description, "説明" %></th>
	<td><%= form.text_field :description %></td>
 </tr>
</table>

app/views/revenues/edit.html.erb
<h2>収入編集</h2>
<%= form_for @revenue do |form| %>
	<%= render "form", form: form %>
	<div><%= form.submit %></div>
<% end %>

app/views/revenues/index.html.erb
<% @page_title = "収入一覧" %>
<h2><%= @page_title %></h2>

<%= link_to "収入の新規登録", :new_revenue %>

<% if @revenues.present? %>
<table>
	<thead>
		<tr>
			<th>収入名</th>
			<th>金額</th>
			<th>備考</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @revenues.each do |revenue| %>
			<tr>
				<td><%= revenue.name %></td>
				<td><%= revenue.value %></td>
				<td><%= revenue.description %></td>
				<td>
				<%= link_to "編集", [:edit, revenue] %>
				<%= link_to "削除", revenue, method: :delete,
					data: { confirm: "本当に削除しますか？"} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<% else %>
	<p>登録されている収入がありません。</p>
<% end %>

app/views/revenues/new.html.erb
<h2>収入登録</h2>
<%= form_for @revenue do |form| %>
	<%= render "form", form: form %>
	<div><%= form.submit %></div>
<% end %>

app/views/revenues/show.html.erb
<h2>収入の詳細</h2>

<%= link_to "編集", [:edit, @revenue] %>
<%= link_to "収入一覧へ戻る", :revenues %>

<table>

	<tr>
    <th>収入名</th>
    <td><%= @revenue.name %></td>
  </tr>
  
  <tr>
    <th>金額</th>
    <td><%= @revenue.value %></td>
  </tr>

	<tr>
		<th>説明</th>
		<td><%= @revenue.description %></td>
	</tr>
</table>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  ここは家計簿アプリのAboutページです。
  このアプリは以下のサイトを参考に作成しています。<br>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a><br>
  <a href="http://inomacreate.com/ruby-on-rails_simple_kakeibo_1/">Inoma Create 
  【Ruby on Rails開発奮闘記】シンプルな家計簿アプリを作る</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  ここは家計簿アプリのContactページです。
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>家計簿アプリへようこそ</h1>

  <h2>
    ここは家計簿アプリのHomeページです。
  </h2>

  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div> 

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<h2>収支登録</h2>

<ul>
	<li><%= link_to "収入設定", :revenues %></li>
</ul>

<ul>
	<li><%= link_to "支出設定", :expenses %></li>
</ul>